name: CI

on:
  push:
    branches-ignore:
      - main
      - 'backport/**'
      - 'create-pull-request/**'
      - 'dependabot/**'
  pull_request:
    types: [opened, synchronize, reopened]
    branches-ignore:
      - 'backport/**'
      - 'create-pull-request/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quick-check:
    name: Quick Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      
      - name: Install minimal dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libboost-all-dev
      
      - name: Verify wrapper
        run: ./gradlew verifyWrapper --no-daemon
      
      - name: Quick build
        run: ./gradlew assemble --no-daemon
      
      - name: Run unit tests only
        run: |
          ./build/native/bin/xtree_tests --gtest_filter=-*Integration*:-*Performance*:-*Stress* || true