name: Dependabot CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'gradle/wrapper/**'
      - '**/*.gradle*'
      - 'buildSrc/**'

jobs:
  dependabot-check:
    name: Dependabot Build Check
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Install minimal dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libboost-all-dev
      
      - name: Verify Gradle wrapper (if changed)
        run: ./gradlew verifyWrapper --no-daemon
      
      - name: Quick build test
        run: ./gradlew assemble --no-daemon
      
      - name: Basic functionality test
        run: |
          if [ -f "./build/native/bin/xtree_tests" ]; then
            ./build/native/bin/xtree_tests --gtest_filter=KeyMBRTest.BasicConstruction:XTreeTest.Creation
          fi